### ISSUE TITLE
Python 3 release

### ISSUE THREAD

**Issue by jairhenrique** [filwaitman/bank-account-validator#11]
@filwaitman can you generate a new release for pypi with python3 support?

**Comment by filwaitman** [comment]
@jairhenrique I'm actually just waiting for your feedback on https://github.com/filwaitman/bank-account-validator/pull/5/files to do so, can you take a look?

**Comment by jairhenrique** [comment]
@filwaitman 🤔 there is no comment there..

**Comment by filwaitman** [comment]
@jairhenrique I forgot to submit it. :facepalm:

**Comment by filwaitman** [comment]
@jairhenrique done!

**Comment by jairhenrique** [comment]
@filwaitman tks!
