### ISSUE TITLE
Use a CI service to run tests

### ISSUE THREAD

**Issue by jairhenrique** [filwaitman/bank-account-validator#3]
Suggestions:

- https://travis-ci.org
- https://circleci.com
- https://github.com/features/actions

**Comment by filwaitman** [comment]
@jairhenrique confesso que faz um tempo que não mexo nesse projeto, mas vou dar uma atualizada nele, colocar travis.CI e codecov (como vc sugeriu). =]

**Comment by jairhenrique** [comment]
@filwaitman abri esse pr para facilitar o coverage #6

**Comment by jairhenrique** [comment]
Fixed
